# name: Dbook

# on:
#   push
#     branches:
#       - main

# jobs:
#   build: 
#     runs-on: self-hosted
#     strategy:
#       matrix:
#         node-version: [18.x]
    
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use node js
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{matrix.node-version}}
#       - name: npm install and start
#         run: |
#           npm install
#           npm start
#         env:
#           CI: true
  
  # deploy:
  #   needs: [build]
  #   runs-on: ubuntu-latest

  #   steps: 
  #     - name: SSH deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username:  ${{ secrets.USER }}
  #         key:  ${{ secrets.KEY }}
  #         port:  ${{ secrets.PORT }}
  #         script: |
  #              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
  #             . ~/.nvm/nvm.sh
  #              nvm instal 14
  #              npm install -g pm2
  #              cd ~/CICD
  #              git pull origin main
  #              npm install
  #              npm run build
  #              pm2 restart api

  # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm start
      - run: npm test
